[package]
name = "TeamSeas-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.39"
serde_json = "1.0.68"
termion = "1.5.6"
